### ISSUE TITLE
Support blacklisting specific checks

### ISSUE THREAD

**Issue by RDIL** [FussyFox/lambdalint#2]
Say I want `pycodestyle` to ignore issue `foo` is that possible?

**Comment by codingjoe** [comment]
Hi @RDIL you can configure pycodestyle as usual via a config file in your repository.
What you can't do however is extend the default behavior of pycodestyle.

Do you have a better example so I could help you better?

**Comment by RDIL** [comment]
@codingjoe is there any documentation for that?  I'm asking because there is this one annoying check I don't want my contributors worrying about, and I can't seem to just be able to flip a toggle.

**Comment by codingjoe** [comment]
Are we will talking about pycodestyle?
https://pycodestyle.readthedocs.io/en/latest/

**Comment by RDIL** [comment]
Yes.
